name: Test Project

on:
  push:
    branches:
      - main

jobs:
  test_build:
    name: Testing if build is successful
    runs-on: windows-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
